### ISSUE TITLE
TINY modal for apps and Get Started

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#1025]
Some times the app icon obscures that title of the app in the title bar; resolved by refresh application. 
![screen shot 2017-11-13 at 2 47 49 pm](https://user-images.githubusercontent.com/5605392/32753476-d7a9155e-c881-11e7-94cc-80c4b9622019.png)

**Comment by caseycesari** [comment]
This is happening because a number of plugins adjust the position of the plugin title, but do so in a way that it effects every plugin. These plugins almost all contain the same snippets of code that are called on activation/deactivation, and they will need to be modified to fix this.

On activation, [this line](https://github.com/CoastalResilienceNetwork/recreation_tourism/blob/1d7bc696ac9b7bbdbd2ea0eb71103abf924ca2bf/main.js#L90) is called, which moves all plugin titles over to the right 25 pixels. On deactivation, [this line](https://github.com/CoastalResilienceNetwork/northcarolina-region/blob/9224ea932f8159aa5dae190eeb129e3d57f8b51f/plugins/community-rating-system/main.js#L53) is called, which moves all plugin titles over to the left 25 pixels.

You only seeing this happen sometimes because if you only activate and deactivate one plugin, the code works as expected. However, after activating another plugin that contains this code, you will soon start to see things get out of sync.

Here's a list of the plugins that do this:

- [Community rating system](https://github.com/CoastalResilienceNetwork/community-rating-system)
- [Ecological effects SLC](https://github.com/CoastalResilienceNetwork/ecological-effects-slc)
- [Migratory blueways](https://github.com/CoastalResilienceNetwork/migratory-blueways)
- [Tuna fisheries](https://github.com/CoastalResilienceNetwork/tuna-fisheries)
- [Benefits explorer](https://github.com/CoastalResilienceNetwork/benefits_explorer)
- [Water security](https://github.com/CoastalResilienceNetwork/water_security)
- [Water funds](https://github.com/CoastalResilienceNetwork/water_funds)
- [Water share](https://github.com/CoastalResilienceNetwork/water_share)
- [Coral reef fisheries](https://github.com/CoastalResilienceNetwork/coral-reef-fisheries)

Some plugins (like [Recreation tourism](https://github.com/CoastalResilienceNetwork/recreation_tourism) and [Natural coastal protection](https://github.com/CoastalResilienceNetwork/natural-coastal-protection)) make this adjustment in a way that does not effect other plugins. You can see an implementation of that [here](https://github.com/CoastalResilienceNetwork/recreation_tourism/blob/1d7bc696ac9b7bbdbd2ea0eb71103abf924ca2bf/main.js#L90).

**Comment by lesserj** [comment]
I had made adjustments in Rec and Tourism and NCP to scope the code just to those plugins.  Looks like I forgot to do it in Coral Reef Fisheries.  I will resolve that one.

This code really does feel like hacking outside of the exposed plugin space.  Ideally, the ability to add a button to the title (or customize the title view completely) would be added directly into the framework so that we can correctly hook into it from the plugin.

**Comment by zferdana** [comment]
Thanks, Jacob. This is actually an enhancement (F) that Azavea will work on as part of this contract: to build TINY modal for app infographics as part of the framework. This should be completed in the next week according to our schedule. Casey C - let us know if this is not the case.

**Comment by caseycesari** [comment]
That's correct. We implemented this for the [launchpad](https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1020), and will implement it for plugins in general this sprint.
