### ISSUE TITLE
Call print process after map has updated

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1062]
Attempt to have `window.print` (used [here](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/develop/src/GeositeFramework/js/Plugin.js#L586)) called by the `update-end` event.

From Jacob Lesser:

> 9. If the map area on the screen is smaller than the map area on the print, the tiles do not finish loading before window.print is called and the map on paper does not fill the allocated size.  I addressed this in my Maine print plugin by loading a css rule to resize the map before calling print to the size I needed on the paper.  I then used the ArcGIS callback methods to resize the map and then wait for it to finish loading before calling the window.print function.  The css to resize the map needed to be a screen rule and not a print rule to make sure that it was executed before window.print suspended execution.

> ```
> this.map.on('update-end', function() {
>     window.print();
> }
> ```

> This has the added benefit of making sure other layers that the user may have toggled on before printing finish loading before calling the window.print function.

**Comment by caseycesari** [comment]
FYI @lesserj 

After experimenting with adding this [within the framework](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/71ef9ecc896178dda5db4b5ddbde76e245f526e5/src/GeositeFramework/js/Plugin.js#L586), I think this should be implemented in the plugin's [postPrintModal function](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/71ef9ecc896178dda5db4b5ddbde76e245f526e5/src/GeositeFramework/js/PluginBase.js#L89). 

I created a demo of this functionality in https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/1067.

I'm recommending this because there are some cases where map doesn't need to update before printing. In these cases, waiting for the `update-end` event to fire doesn't make sense. The Maine region/future habitat v2 plugin implementation get around this by checking if the map is updating before binding print to the `update-end` event. However, this requires adding a `setTimeout` call. If you immediately check if the map needs to be updated after adding a layer, for example, the map doesn't appear to need to be updated. This leads to a complicated implementation and a delay in the print process on the framework side for a case that may not happen all the time.

This also ensures that there are no setTimeouts in the core plugin print process. think it’s worth striving to maintain this since adding setTimeouts to the core process can introduce timing issues and race conditions.

**Comment by lesserj** [comment]
@caseycesari Almost every plugin that uses this print function will need this feature, so the framework is the most appropriate place for it.  If you look at the description above, the primary issue has to do with ensuring the map fits in the printable area.  If the map in the screen area is smaller than the map in the print document, without resizing the map, the map will not fill the allotted space and there will be extra white space on the print page.  The map needs to be resized at least as large as the allocated print size in both the x and y axis and all the tiles need to be loaded.  This will not be unique to any plugin, but will be needed in almost all plugins where the map on the page is larger than a couple tiles by a couple tiles.  You can see how this fails with the current development implementation and the North Carolina region at http://dev.maps.coastalresilience.org/northcarolina/.  If you call the print function in the future habitat on a large screen, the result will look fine.  If you call it on a smaller screen, like a laptop, the right and bottom of the map will be cut off because those tiles haven't loaded.  You can also resize your browser window smaller to trigger the same result.

I addressed this in Maine by resizing the map using css to be as large (or larger) than the print area before the window.print function was called and used the callbacks to ensure any additional tiles were loaded.

**Comment by caseycesari** [comment]
@lesserj Thanks for the feedback.

I'm trying to see the current behavior on the North Carolina region, but I don't see the future habitat plugin. 

Is it displayed under a different name?

https://github.com/CoastalResilienceNetwork/northcarolina-region/blob/development/plugins.json
