### ISSUE TITLE
Create development server

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1085]
We'll need a development server to replace the server that comes along with Visual Studio.

- Make use of the SimpleHTTPServer
- Sticking with our other project conventions, this should live at `./scripts/server`.
- Create a new `index.html` based off the existing `index.cshtml`. This should probably live at https://github.com/CoastalResilienceNetwork/GeositeFramework/tree/master/src/GeositeFramework/index.html, but consider other locations.
- The new index page should be feature incomplete, but not broken. It should be able to be served from the development server.

**Comment by mmcfarland** [comment]
Are you planning to use webpack features to also do bundling or other compilation tasks as part of the build?  If not, bringing webpack in for just the dev server may be overkill and a simple http server might be an easier solution.  If it will be integrated into a larger pipeline, it'd be good to specify some of that detail on this issue so that the implementor is able to use it as context about how else it's going to be used.

**Comment by fungjj92** [comment]
The top-level issue description has been updated since merging the ADR, going with a python environment (to clarify the above suggested to use webpack/JS)
