### ISSUE TITLE
Determine if CSVhelper is still utilized

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#1091]
- https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Helpers/CsvHelper.cs
- https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Tests/DownloadTests.cs
- https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Controllers/DownloadController.cs

**Comment by mmcfarland** [comment]
This probably is very underutilized, but if plugins do use it, we can probably re-create the functionality in JS now that we download data directly from the a client data uri.  In 2014 this had limited support and it was basically just a way to post data back to the server to have it downloaded (with some formatting to csv).

**Comment by mmcfarland** [comment]
The URL to scan for is https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Controllers/DownloadController.cs#L18

**Comment by caseycesari** [comment]
@mmcfarland I may be misremembering, but I thought you posted somewhere what to search for to find if plugins are using this feature. Do you recall doing that?

**Comment by mmcfarland** [comment]
The feature is exposed through the `app` object passed to the plugin.  You should be able to search for either `downloadAsCsv` and `downloadAsPlainText`.  

https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/e67a36f933d9e87475a73d996f54a00c57931e38/src/GeositeFramework/js/Plugin.js#L80-L81

I can say for sure it's included in the Draw & Report plugin, but I'm not sure how many CoastalResilience plugins use that.  It's used in the Louisana Freshwater region, which is a different org.

**Comment by fungjj92** [comment]
It looks like the CSVHelper is used in the regional-planning plugin, which is avail in practically every region site. A search for `downloadAsCSV` across the CoastalResilienceNetwork's repos https://github.com/search?q=downloadAsCsv+user%3ACoastalResilienceNetwork&type=Code

The followup card to this will be to  actually port the CSVHelper logic, then.

**Comment by mmcfarland** [comment]
Although, it may not be actually used.  A test of a configured layer shows that the backend report configuration is invalid and fails:

![screenshot from 2018-10-09 15 44 04](https://user-images.githubusercontent.com/1014341/46694259-378b8680-cbda-11e8-87b7-43fbbfbe792a.png)

**Comment by fungjj92** [comment]
Thanks for filling in the blanks! On second evaluation:
https://github.com/search?q=org%3ACoastalResilienceNetwork+reports+reportDbLayerName&type=Code

Only Maryland, NCS, and Virginia regions are set up to use the reports feature. However, Virginia errors as pictured above. [NCS](http://maps.oceanwealth.org/) has no reports configured, validly anyway. And Maryland doesn't exist ?? The repo is a little funny, it appears titled with Connecticut but the repo and regional planning layers reference Maryland. It's possible this project isn't live.

Csvhelper can probably be sunsetted since where it appears to be used,  it isn't even configured or is broken. This has probably been true for quite some time, and we have yet to receive a bug report from TNC. This leads me to believe the feature isn't useful anymore. Worth mentioning this to them in summary.

**Comment by caseycesari** [comment]
Thanks for looking into this @fungjj92 @mmcfarland. Let's defer on porting this over to the static site for now. If it's needed at some point in the future, we can port it then.
