### ISSUE TITLE
Develop Internationalization scheme

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#589]
Give http://i18next.com/docs/ a look.

 * [ ] Update region schema
 * [ ] Add i18n module
 * [ ] Replace all hard-coded text/date/number formats
 * [ ] Create sample language string table
 * [ ] Create example Jenkins build?

**Comment by rajadain** [comment]
There are fundamentally three kinds of places where strings need to be replaced:

 1. Direct strings in the native app, such as ["Split View"](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/Views/Home/Index.cshtml#L199)
 2. Region strings, such as ["Flower Garden Banks Marine Sanctuary"](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/region.json#L40)
 3. Plugin strings, such as ["Clear All"](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/layer_selector/templates.html#L6)

1 and 3 should support multiple languages and locales. The path of localization maps should be devised and followed as a convention, with minimal configuration on the developer's part, so that plugin developers can just stick a translation file in a spot and have the rest of their plugin work as is.

Regarding 2, if the region supports only one language and locale, then nothing needs to be done. However, if a region is to support more than one language or locale, then we'll need to figure out where to put translation strings for those specified in the region's configuration.

**Comment by rajadain** [comment]
A basic test app for internationalization is available here: https://github.com/rajadain/i18next-test

I've been using it to play with the [i18next](http://i18next.com/) library.

**Comment by rajadain** [comment]
The approach to declaratively describe translation keys, like so:

```html
<a class="switch-screen i18n" data-i18n="[title]sidebar.viewOnlyMap1;sidebar.fullMap"></a>
```
Gets translated to

```html
<a class="switch-screen i18n" data-i18n="[title]sidebar.viewOnlyMap1;sidebar.fullMap" title="View Only Map 1">Full Map</a>
```

once

```js
$('.i18n').localize();
```

gets called. Currently, we do that once during app init. However, in the case of templates, this needs to be executed after each render.

**Comment by kdeloach** [comment]
Declarative syntax could be a nice addition if we don't have to call `localize()` each time a template is rendered. At minimum, there should be a function that can handle translations for things outside the DOM (ex. `alert(__("Translate me"))`).

**Comment by rajadain** [comment]
I think the current approach is not terrible, although probably could be a little less verbose https://github.com/rajadain/GeositeFramework/commit/ede7e5ec397d936fa55ef9f2f1600405e6c35eeb (context: https://github.com/rajadain/GeositeFramework/commits/feature/internationalization).

The plugin does add a global translation method, that can be directly accessed with:

```js
alert($.t('translationKey'));
```

The instance of `i18next` can be accessed via:

```js
$.i18n;
```

These are default initializations. For a complete list, see https://github.com/i18next/jquery-i18next#initialize-the-plugin

I'm going to start on the other static parts of the app before moving on to an architecture for the plugins.

**Comment by kdeloach** [comment]
We should verify that that i18n function is accessible to plugins as well. Note that each plugin can potentially shim a different version/instance of jQuery (ex. https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/plugins/measure/main.js#L11).

Something else to note is that we should omit context from these keys. "Full Map" will be translated the same no matter where it appears on the page. Another reason to omit context is to prevent duplicate translation entries because the same phrase happens to appear in 2 different contexts. Let me know if this makes sense or not.

**Comment by rajadain** [comment]
## Overview

Okay, we're switching to a phrase-based approach opposed to a context-key-based approach, as per Kevin's comment above. In this case, we will attempt to translate a phrase, such as "Full Map", and if a translation is found it will be used, otherwise it will fallback to the key itself:

```js
// translation.json
{
    "Full Map": "Full Map Translated"
}

// Usage
i18next.t('Full Map'); // "Full Map Translated"
i18next.t('Hide Map'); // "Hide Map"
```

## Approach

Since we can only use one JSON per locale, but we may have multiple ones (from the core app, and the various plugins), I suggest we use a technique that compiles one JSON per locale on `App_Start`. Consider the following directory structure:

```
/

    locales/
        en.json
        es.json

    plugins/
        p1/
            locales/
                en.json
                es.json
        p2/
            locales/
                en.json
        p3/
        p4/
            locales/
                en.json
                de.json

    languages/
        en.json
        es.json
        de.json
```

In this case, we have two core translation files under `/locales/`, namely `en` and `es`. Different plugins have different translation files: `p1` has the same as core, `p2` has only `en`, `p3` has none, and `p4` has `en` and `de` (which is extra and not in core).

At either deploy time or app start, we compile all the found `locale/*.json`s into one per language, into a new folder `/languages/`. Thus, we have

 * `/languages/en.json` compiled from core, `p1`, `p2`, and `p4`
 * `/languages/es.json` compiled from core and `p1`
 * `/languages/de.json` compiled from `p4`

The final language is specified in `region.json`, and is loaded accordingly:

```js
// region.json
{
    "language": "es",
    ...
}

// App.js
function internationalize(lng) {
    var options = {
        lng: lng,
        backend: {
            loadPath: 'languages/{{lng}}.json'
        },
        ...
    },
    callback = function() { ... };

    i18next.use(i18nextXHRBackend).init(options, callback);
}

// initialization
internationalize(N.app.data.region.language);
```

## Plugin Usage

Plugins will have access to `i18next` from the global scope, so they can use it automatically in their JavaScript files:

```js
i18next.t('Full Map'); // "Full Map Translated"
```

Since we are doing phrase based translation, if a translation exists in the `{{lng}}.json` file it will be used, else it will fallback to the key.

For using the `data-i18n` attribute, plugins _must_ use the global `$` and include some call to `$(selector).localize()` in the plugin's equivalent of a render method. This is still under investigation.

## Collisions

What happens in case a plugin tries to redefine a phrase already defined in core? Should it overwrite the core definition? Should we ignore it? Or should we use multiple instances of `i18n`, one for the core, and one per plugin, so they can have localized internationalization?
