### ISSUE TITLE
Enable default size configuration in main.js

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#643]
Enable plugin developers to configure the default size (height & width) of plugin windows in main.js.

**Comment by kdeloach** [comment]
Is this for Regional Planning? Plugins can already override width and height (https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/master/src/GeositeFramework/js/PluginBase.js#L48).

**Comment by mmcfarland** [comment]
This is for adding a configuration file which the plugin reads from.  This configuration file can then be added to a region repo so that it overrides the default plugin based config and lets them override any plugin settings without touching the code.

I've actually already got an issue for this, closing in favor of https://github.com/CoastalResilienceNetwork/regional-planning/issues/15
