### ISSUE TITLE
custom legend

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#657]
The following seems to be a common theme since migrating over to the new framework and legend:

I’m having a hard time figuring out the best way to override the new legend plugin modifications.  It isn’t picking up our custom class breaks like the old one did, but is instead using the default style from the server.  I can’t find a clean way with the plugin API to override the legend container and legend title for our plugin.  Is there a built in way that this should be done?
 
I can create custom content in the legend using this method:
 
$(this.legendContainer).html("Custom legend here");
 
But that doesn’t get rid of the layer-legend that is automatically loaded when we add the layer to the map, which we don’t want to show as is.
 
I’d appreciate any pointers you might have on how we are supposed to do this, before I try and find an “alternative” solution.

**Comment by kdeloach** [comment]
Could you provide the name of a reference plugin we could use to reproduce the problem?

**Comment by zferdana** [comment]
sure, the Natural Coastal Protection plugin on http://dev.maps.oceanwealth.org/ is experiencing this problem

**Comment by dharlan** [comment]
HydroFlows legend has boxes around each legend item, causing the legend to get larger than needed.    This can been see here http://54.241.26.242/mississippi-dev/.

**Comment by mmcfarland** [comment]
@zferdana This appears to be due to the use of a custom renderer for the layer.  Since we ditched the confining ESRI Legend widget we are making requests directly to the legend endpoint, which are not reflecting the custom class breaks.  This may be more than a quick fix to integrate with the custom renderer.

An interim solution using the available framework features might be:
1. Disable the framework from auto showing the plugin layer in the legend by [setting `showServiceLayersInLegend = false`](https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/71c05132c2762be06b439c09abb72cd116d31e5d/src/GeositeFramework/js/PluginBase.js#L30) in your main.js file
2.  Add a custom legend as demonstrated here:  https://github.com/CoastalResilienceNetwork/regional-planning/commit/b7098729032b0a9ce1ad733dc009ef37639c50df

**Comment by mmcfarland** [comment]
@dharlan It looks like HydroFlow is using a custom legend (like I described above), but the custom legend it puts in is a `<table />` html element with no particular styling classes.  The boxes are the table outline and padding.  For custom legends, the framework doesn't apply automatic styling because the contents could be anything.  I would recommend that the plugin developer add styling classes (or inline styles) to the html content they are putting in the legend and then including appropriate styles in the plugin css to make it look the way they intend.

**Comment by dharlan** [comment]
Thanks Matt.  I will relay to the developer.  She should be looking at this today.

**Comment by ksparks44** [comment]
HydroFlow is using the ESRI Legend Digit (esri/dijit/Legend).  I agree that it is rendering as a table, but I don't think I have easy access to the styling.  Can you provide more information about how to interact with the legend end point you mentioned?

**Comment by mmcfarland** [comment]
@ksparks44 We can probably update the styling for the framework, I didn't realize the markup was coming from an esri dijit directly.  I'm going to add

```css
.esriLegendService table, .esriLegendService tbody, .esriLegendService tr, .esriLegendService td {
    border: 0;
    margin: 0;
    padding: 0;
}
```
to neutralize the table styling within the legend.

@dharlan I'll let you know when to rebuild the framework to test the fix.

**Comment by dharlan** [comment]
Thanks Matt!

**Comment by mmcfarland** [comment]
@dharlan @ksparks44 #658 will clean up the legend nicely, but there are some custom style rules in HydroApp that should be removed if you want some additional padding to be condensed.  There are some inline styles here:  
https://github.com/FreshwaterNetwork/HydroFlow/blob/master/Templates.html#L3-L14

which cause additional padding that isn't controlled by the framework.

**Comment by mmcfarland** [comment]
More specifically: https://github.com/FreshwaterNetwork/HydroFlow/blob/master/Templates.html#L6-L7

**Comment by mmcfarland** [comment]
@dharlan - master and develop both have the fix applied, feel free to redeploy.

**Comment by dharlan** [comment]
@mmcfarland @ksparks44 Legends look much better.  Boxes are gone.  Oysterflows legend gets really wide compared to old framework. http://maps.freshwaternetwork.org/louisiana/ http://54.241.26.242/louisiana-dev/  You can see the difference between dev and prod here.  Definitely looks cleaner but the large legend covers some map space.

**Comment by dharlan** [comment]
@ksparks44 I removed the legend padding and margin from templates.html (oysterflows) on the dev site and it definitely shrunk the legend down some.  I have not touched the app repo itself just the build I did this morning.

**Comment by dharlan** [comment]
@ksparks44 I'm also noticing that the Sabine station markers are not showing on the map until the scenario is run.

**Comment by ksparks44** [comment]
@dharlan That appears to be happening in production as well – so I don’t think that is related to this legend issue.  I am looking at the Sabine right now.  I think it looks good – I’m just trying to see if I can track down the code that makes the legend  wide as you are using it (probably dynamic padding somewhere).

I think the Hydro Flow App is looking OK too.  For the hydro flow app – be sure to update GIT with your Templates.html changes.  I noticed the version I pulled down from git doesn’t have all of the text additions that you made.

**Comment by ksparks44** [comment]
@mmcfarland Thank you for the update!  I really appreciate the help.

**Comment by dharlan** [comment]
@ksparks44 yes I'm keeping a version of templates for HydroFlow in each of the region repos so I can customize the text.  As far as the Sabine station markers, it looks like the Calcasieu markers are images that are not actually part of the map service.  Is that the case for the Sabine markers as well?  I agree that it is not a legend issue and likely not due to the new framework version.

**Comment by dharlan** [comment]
@ksparks44 Removed styling on OysterFlow legend. Seems to look fine.  Now just need to figure out Sabine markers.

**Comment by mmcfarland** [comment]
@ksparks44 no problem at all :+1:
