### ISSUE TITLE
Look into how plugin overrides effect new size settings

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#711]
- Should we whitelist certain settings?
- `height` is no longer supported, but it will still be applied if it's in `override.json`.

**Comment by kellyi** [comment]
Trying out this `overrides.json` file in the Identify Point sample plugin:

```
{
    "name": "Identify Point Sample Plugin",
    "description": "A sample plugin used to identify a point on the map",
    "height": 300,
    "width": 1300,
    "resizable": true,
    "hasCustomPrint": true,
}
```

... and it looks as if the width and height properties and some of the others are being ignored correctly. I do see the custom name property in a popup when I mouseover the plugin in the sidebar, however.

**Comment by kellyi** [comment]
Actually, scratch that. It looks like that's being ignored too. Going to check to make sure I have the `overrides.json` file included correctly.

**Comment by kellyi** [comment]
For my reference, here's how the overrides seem to be set: https://github.com/CoastalResilienceNetwork/regional-planning/blob/master/main.js#L65

Going to try that with the Identify Point plugin.

**Comment by mmcfarland** [comment]
I'm not sure we need to focus on this.  Overrides aren't a feature of the framework, it's just a config file that allows this plugin to load non-default values from.  I included an example overrides file in the `regional-planning` repo because it's a plugin that is widely used, and it allows configuration when used with the build system.  A region developer could include their own overrides.json file in their `region-repo` which would allow them to change the name and a few other settings per region (the build system was designed not to copy over region repo plugin files).  If a plugin wasn't developed with an external config, this wouldn't be possible - but the framework doesn't manage the process either way.  

I think we just remove the `height` attribute from the regional-planning overrides example file, and then probably remove `height` altogether from the plugin spec, since it's not a setting that can be applied anymore.

**Comment by kellyi** [comment]
> I think we just remove the height attribute from the regional-planning overrides example file, and then probably remove height altogether from the plugin spec, since it's not a setting that can be applied anymore.

Got it. I'll update regional-planning to drop the overrides file. I've already updated the wiki documentation to remove `height` from the plugin settings:
 
https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Plugin-Settings
