### ISSUE TITLE
Map utils should close when clicking away or clicking the plugin button again

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#738]
The current behavior relied on a close button being added to the plugin button when it was activated. This was done away with in #733 because it's not that intuitive. 

The plugin should deactivate when clicking in another spot in the app or when the plugin button is clicked agin.

**Comment by jfrankl** [comment]
Here's the button Casey is referencing:

![image](https://cloud.githubusercontent.com/assets/1809908/20366754/7dce9f42-ac1a-11e6-83dd-624a1f5e53d8.png)

**Comment by kdeloach** [comment]
I think that the only way to do this is to create a shadow div behind the menu to capture mouse events. However, this kind of breaks the plugin paradigm, since plugins should generally be sandboxed to prevent updating anything outside of the context of that plugin.

This may be a sign that making this a "plugin" was a mistake and that this component should just be part of the core framework.

**Comment by kdeloach** [comment]
Also, this plugin should **not** save any state. If you select "Save & Share" then load that url, the map utils plugin will be opened upon page load. I think this is another argument for making this part of the core framework instead of a plugin.

**Comment by kdeloach** [comment]
Something else to note is that due to a recent change, when you click on the map utils plugin twice, it will appear "active" even though the menu is closed.

![image](https://cloud.githubusercontent.com/assets/43062/21021814/2d4a2886-bd48-11e6-9bf5-579864d22a06.png)
![image](https://cloud.githubusercontent.com/assets/43062/21021818/33ab8922-bd48-11e6-9c7a-d66785a030d9.png)

**Comment by kdeloach** [comment]
I also noticed that sidebar plugins will always be closed when restoring from a saved state. The map_utils plugin closes other active plugins when it is clicked.
