### ISSUE TITLE
REST Service bugs

### ISSUE THREAD

**Issue by laflessn** [CoastalResilienceNetwork/GeositeFramework#768]
1. Layer names for REST services come over as the root service name in the legend, which can be cryptic with underscores.  Example in gulfmex > Flood & SLR app > NOAA Coastal Flood Exposure > Sea Level Rise scenarios > select any layer.  Is there a way to set the legend names of a REST service to be the same as the display name in the json? 

2. Some REST services will remain on the map even if you turn the layer off or reset the layers or close the app. Example in gulfmex > Flood & SLR app > NOAA Coastal Flood Exposure > Storm surge scenarios > storm type > turn on any scenario then try to turn off, reset, exit app. 

3. Also, in the same storm surge example as above, all service layers turn on at the same time no matter which scenario you actually turn on. The combine function was not used in the json, and all layers should be able to be turned on separately.

**Comment by kdeloach** [comment]
Item 1 is by-design since the legend is generated using information available through the ESRI ArcGIS JavaScript API. To change this we would have to extend the map framework to allow plugins to attach metadata to map layers.

Items 2 and 3 seem to be due to server latency. The regional planning plugin should work as expected If you wait 15-20 seconds for each layer to load.

**Comment by caseycesari** [comment]
Migrated to https://github.com/CoastalResilienceNetwork/regional-planning/issues/94
