### ISSUE TITLE
Can't scroll Launchpad in IE 11 or Firefox

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#808]
Observed in IE 11 and Firefox 50 on Windows 10

**Comment by kellyi** [comment]
This is also happening on Firefox for OS X but not Safari or Chrome for OS X, which probably means webkit vs non-webkit browsers.

**Comment by kellyi** [comment]
I believe this occurs because the launchpad plugin is missing a `height` property -- it seems like we do set that in regional-planning, which enables it to scroll on Firefox and IE11. I tried out `height: 80vh` so far and it worked to force the scroll but didn't look quite right, so I'm going to test out some other values.

**Comment by kellyi** [comment]
`height: 100%` turns out to be too large, as it looks like the value's 100% of the viewport height and then the launchpad pushes below the bottom margin without being scrollable. However, if you hit the space bar in FF with the height set that way, it will scroll the plugin content bar and the entire map down to the bottom such that the bottom of the plugin will be visible.

**Comment by mmcfarland** [comment]
Re: height, is something like this appropriate?  https://github.com/CoastalResilienceNetwork/GeositeFramework/blob/prototype/src/GeositeFramework/css/main.css#L938

**Comment by kellyi** [comment]
Yeah! Looks like `height: calc(90vh - 60px);` seems to work.

**Comment by ajrobbins** [comment]
I just observed this again on Firefox and IE 11, and TNC reported it in IE11 as well.

**Comment by kellyi** [comment]
I believe @mmcfarland just made a fix to the regional-planning `prototype` branch's scroll behavior that might potentially work here, too.

**Comment by lewfish** [comment]
This also seems to happen on Chrome in Windows.

**Comment by mmcfarland** [comment]
Don't mean to poke my nose in ongoing work, but this turns out to be the same problem I had with regional planning.  Update this particular style should resolve it:

```css
.launchpad-plugin {
    padding: 10px;
    height: 100%;
    overflow: auto;
}
```

**Comment by lewfish** [comment]
This fixes it on Chrome, but not IE11. It looks like the PR I did to make the layer info box visible is causing further issues than can be fixed with this patch.

**Comment by lewfish** [comment]
I think I know how to fix it now.
