### ISSUE TITLE
Determine tour failure for virgina-region

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#854]
The build for virginia-region doesn't produce a working Tour feature.  Investigate why, it may have something to do about misplaced content for TourInfo.cshtml  

See: https://github.com/CoastalResilienceNetwork/GeositeFramework/wiki/Site-Tour

**Comment by rajadain** [comment]
Shares a point with #854

**Comment by rajadain** [comment]
The generated TourInfo.cshtml is identical to the base framework. The true issue lies elsewhere. Investigating ...

**Comment by rajadain** [comment]
Deleting this line fixes it: https://github.com/CoastalResilienceNetwork/virginia-region/blob/master/region.json#L8

I think a link with the same ID was being added twice to the page, one from the built-in and another from the configuration. Since IDs have to be unique on a page, duplication made the click binding fail.

If they would like to be able to add custom help links in the header that trigger the same thing, we would have to switch to using classes for the click binding instead of an ID. That would be an enhancement.
