### ISSUE TITLE
Hide Save and Share save code

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#871]
A regression has allowed this to be on by default.  Should be hidden until "Get it here" is clicked.

**Comment by kellyi** [comment]
Shares a point with #877

**Comment by kellyi** [comment]
Visibility issue was due to a typo in the div id plus a missing CSS rule to hide it to start. I'm not sure how this worked in the prior version of the framework, but should the "Get it here" text & link hide when after it's clicked and the save code has been displayed?

Before clicking:

![screen shot 2017-02-16 at 9 59 00 am](https://cloud.githubusercontent.com/assets/4165523/23026361/066bea42-f42f-11e6-9111-a53a600af47b.png)

After clicking:

![screen shot 2017-02-16 at 9 59 11 am](https://cloud.githubusercontent.com/assets/4165523/23026369/0b1ebd80-f42f-11e6-98a7-f5c25e13f127.png)
