### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#872]
I checked the latest build of NJ-Spanish (new framework) and here are some places where we're not using the i18n key for translation:

- ~~Coastal Resilience title (`nav-main-title`)~~
- ~~Region subtitle (`nav-region-subtitle`)~~
- ~~Hamburger menu items: Legal Disclosure, Other Regions (I think we should have translation options for the region names as well)~~
- ~~Basemap options (`basemap-selector-title` and dropdown options)~~
- Search input text (`search_input`)
- Legend: "View 1 more" and "view less" - I couldn't figure out how to get these to show with regional planning, but I think they do in the Natural Protection plugin for 100 year flood

**Comment by mmcfarland** [comment]
From the above list, the following are all defined in the configuration for a region, and don't really make sense to translate automatically.  The region manager would simply add the values using the language she intends for display; we'd otherwise be forcing them to put in English only to translate it later.  Additionally, since these are user configurable, we can't load up translation tokens ahead of time.  This is already how they're handling configuration based "translation" (https://github.com/CoastalResilienceNetwork/mar-region/blob/master/region.json#L5)

* Coastal Resilience title (nav-main-title)
* Region subtitle (nav-region-subtitle)
* Hamburger menu items: Legal Disclosure, Other Regions
