### ISSUE TITLE
Search message is blocked by basemap selector

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#905]
![image](https://cloud.githubusercontent.com/assets/1042475/23667543/36700bc2-032c-11e7-9dd3-009fceab92ce.png)

![image](https://cloud.githubusercontent.com/assets/1042475/23667563/431562be-032c-11e7-8db5-8de0b103efb8.png)

**Comment by kellyi** [comment]
I checked into this and it appears that we have fixed it in passing between March 2017 and now:

Chrome:

![screen shot 2018-08-29 at 10 24 27 am](https://user-images.githubusercontent.com/4165523/44794094-bc17cd80-ab75-11e8-98e0-4f98f11a0df1.png)

Firefox:

<img width="331" alt="screen shot 2018-08-29 at 10 24 51 am" src="https://user-images.githubusercontent.com/4165523/44794119-c9cd5300-ab75-11e8-8e98-700dbda4ac20.png">

Safari:

<img width="342" alt="screen shot 2018-08-29 at 10 25 13 am" src="https://user-images.githubusercontent.com/4165523/44794148-d651ab80-ab75-11e8-9c7b-cdfea5d50693.png">

The geocoder input does not currently render in IE11, but that problem is encompassed by the work for #1076.

I'm going to move this card to verified.
