### ISSUE TITLE
Get Started partner logo formatting

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#957]
Comments from Virginia - can we add any flexibility to partner logo array? http://dev.maps.coastalresilience.org/virginia/ 
It looks like they’re being placed at around 70 pixels tall, regardless of how wide they are. So for the images that are wide, they’re actually being stretched and thus pixelated. For example when I resized the Arcadis logo to 100 pixels wide, that makes it only 17 pixels tall. But the app is stretching it to ~70 pixels tall, which makes it ~400 pixels wide. The attached set is optimized for this case but I think this is something you should raise with Azavea because we need more flexibility in sizing the logos since this will result in some logos looking more prominent than others (and in our case the wrong ones looking prominent).

**Comment by caseycesari** [comment]
Image for reference: 

![image](https://cloud.githubusercontent.com/assets/1042475/25387006/3c7f2a0c-2997-11e7-9748-e1182a678f47.png)

**Comment by zferdana** [comment]
Thanks, Casey, for addressing this. Can you give me a sense of when you anticipate this getting resolved, and you all push the develop framework branch into master?

**Comment by ajrobbins** [comment]
The 60px logo height helps enforce a uniform visual experience with the logo section. This is difficult since logos are so idiosyncratically sized.

Resolved with best practice:
- If possible, choose logo versions that are circular or square
- If logos are rectangular or an otherwise odd shape, add padding as necessary to size them appropriately with the 60px height
