### ISSUE TITLE
Add callback for custom print content

### ISSUE THREAD

**Issue by caseycesari** [CoastalResilienceNetwork/GeositeFramework#986]
This will give plugin developers an opportunity to add custom content to the print area before browser print it initiated.

**Comment by caseycesari** [comment]
Hi @lesserj. I was looking into this issue that came out of meeting last week.

I recalled that we expose the `beforePrint` function to plugins so that plugins can add custom content to the print layout. Here's an example from the future habitat plugin https://github.com/CoastalResilienceNetwork/future_habitat_v2/commit/aa3535f706ae25d675bc44546bf2a644605b18fe. 

Should this methodology be modified? Or is there some other change that will give you what you are looking for as a plugin developer?

**Comment by lesserj** [comment]
Hi @caseycesari I initially started using the beforePrint callback when building Maine before having to bail out and build our own print function.  Part of the custom print we needed to implement required the options of inserting custom text provided by the user (text boxes) and toggles (checkboxes) so the user could hide/show certain elements on the page when they were given the custom print dialog. I tried working around this by injecting content directly into the print options box on load.  There was not a callback to do this, and because of how the modal was designed, I had to use timeouts, which wasn't reliable.  We need a way to inject content into the print options modal that can then be queried from the beforePrint function so we can provide options for the user to customize their print.

I don't remember specifically how well the beforePrint function worked regardless of the custom options we needed in the print option box.  In our print version in Maine, I created a new print.html template with all of the elements that I needed and copied run time specific data into that template.  This could be generalized for a framework option by allowing the developer to create their own template file with template variables object that could be specified in the beforePrint function.

The last big change regarding content we did for Maine was reusing the main map rather than generating a new map, which is what the plugin does.  We had a lot of custom content on our map, and rebuilding a new map with identical content was prohibitively time consuming.  Simply adjusting the dimensions and styling of the main map for print, and resetting when print was done was much simpler.   This does get into task item 4 regarding preserving zoom extent and layer visibility.  That is an issue regardless of whether we reuse the main map, or create a new print only map.  Lastly, we had to make the main map and the print_template play nicely with each other.  The print template was designed with css to fit to a single landscape letter size piece of paper, with the main map absolutely positioned on top of it.  Some flexibility would need to be added here to support multiple page sizes.
